server:
  port: 12001
  servlet:
    context-path: /ai-server

#配置项目的数据源
spring:
  config:
    import:
      - "optional:nacos:bj-common.yaml?refreshEnabled=true&group=${BJ_NACOS_CONFIG_GROUP:BJ-GROUP}"
      - "optional:nacos:bj-ai.yaml?refreshEnabled=true&group=${BJ_NACOS_CONFIG_GROUP:BJ-GROUP}"
  application:
    name: bj-ai
  main:
    allow-bean-definition-overriding: true
  mvc:
    pathmatch:
      #      matching-strategy: ant_path_matcher
      matching-strategy: path_pattern_parser
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  data:
    redis:
      address: ${BJ_REDIS_ADDRESS:redis://localhost:6379}
      host: ${BJ_REDIS_HOST:localhost}
      port: 6379
      database: 0
      lettuce:
        pool:
          enabled: true
          max-active: 32
          max-idle: 16
          min-idle: 4
          max-wait: 2000ms
      password: ${BJ_REDIS_PASSWORD:}
  cloud:
    nacos:
      server-addr: ${BJ_NACOS_SERVER_ADDR:localhost:8848}
      username: '${BJ_NACOS_USERNAME:nacos}'
      password: '${BJ_NACOS_PASSWORD:}'
      discovery:
        server-addr: ${BJ_NACOS_SERVER_ADDR:localhost:8848}
        username: '${BJ_NACOS_USERNAME:nacos}'
        password: '${BJ_NACOS_PASSWORD:}'
        enabled: true
        namespace: ${BJ_NACOS_NAMESPACE:bj}
        group: ${BJ_NACOS_DISCOVERY_GROUP:BJ-GROUP}
      config:
        file-extension: json

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
    qos-port: 22300
    logger: slf4j
  scan:
    base-packages: com.djj.bj.ai.application.dubbo
  protocol:
    name: dubbo
    port: 20887
    threads: 200
  registry:
    address: "nacos://${BJ_NACOS_SERVER_ADDR:localhost:8848}?namespace=${BJ_NACOS_NAMESPACE:bj}&register-consumer-url=true"
    register-mode: instance
    username: ${BJ_NACOS_USERNAME:nacos}
    password: ${BJ_NACOS_PASSWORD:}
    group: ${BJ_NACOS_DISCOVERY_GROUP:BJ-GROUP}

bj-ai:
  context:
    max-rounds: ${BJ_AI_CONTEXT_MAX_ROUNDS:10}
    ttl-hours: ${BJ_AI_CONTEXT_TTL_HOURS:24}
  type: chatgpt
  chatgpt:
    key: ${BJ_AI_CHATGPT_KEY:}
    api: ${BJ_AI_CHATGPT_API:https://api.openai.com/v1/chat/completions}
  chatglm:
    key: ${BJ_AI_CHATGLM_KEY:}
    api: ${BJ_AI_CHATGLM_API:}
  claude:
    key: ${BJ_AI_CLAUDE_KEY:}
    api: ${BJ_AI_CLAUDE_API:}
  tongyi:
    key: ${BJ_AI_TONGYI_KEY:}
    api: ${BJ_AI_TONGYI_API:}
  palm:
    key: ${BJ_AI_PALM_KEY:}
    api: ${BJ_AI_PALM_API:}
  xinghuo:
    key: ${BJ_AI_XINGHUO_KEY:}
    api: ${BJ_AI_XINGHUO_API:}
  wenxin:
    key: ${BJ_AI_WENXIN_KEY:}
    api: ${BJ_AI_WENXIN_API:}
  hunyuan:
    key: ${BJ_AI_HUNYUAN_KEY:}
    api: ${BJ_AI_HUNYUAN_API:}
