server:
  port: 8877
  id: 1
  servlet:
    context-path: /bj

spring:
  data:
    redis:
      address: ${BJ_REDIS_ADDRESS:redis://localhost:6379}
      host: ${BJ_REDIS_HOST:localhost}
      port: 6379
      database: 0
      lettuce:
        pool:
          enabled: true
          max-active: 32
          max-idle: 16
          min-idle: 4
          max-wait: 2000ms
      password: ${BJ_REDIS_PASSWORD:}

websocket:
  enable: true
  port: 8878

tcpsocket:
  enable: false # 暂时不开启
  port: 8879

heartbeat:
  count: 10

jwt:
  accessToken:
    secret: ${BJ_JWT_ACCESS_SECRET:change-me-access}

rocketmq:
  name-server: ${BJ_ROCKETMQ_NAME_SERVER:localhost:9876}
  producer:
    group: bj-server-group

message:
  mq:
    type: rocketmq


distributed:
  cache:
    type: redis
  lock:
    type: redisson

redis:
  arrange:
    type: single # single or cluster
